
let b=[1,2,4,5,6,7,8,9,10]
let d=[10,9,8,7,6,5,4,3,2,1]
  console.log(b);
  console.log(b[2],d[6]);

  // Array Program
  let c=["Priyanka","Suman","Priya","Puja","Pawiranjan","Ritesh"]
      console.log(c);
      console.log(c["5"]);
      console.log(c[2]);
      console.log(c[4]);
      console.log(c[0]);

// Array Program
 const GAME=["Cricket","ludo","khokho","Kabbadi","Badminton","Tennis"]
    console.log(GAME);
    console.log(GAME[1]);
    console.log(GAME[5]);
    console.log(GAME[2]);

//Array Program
 const food=["Chole Bathure","Manchurian Chowmin","Veg Kofta","Pulaw"]
 const price=[200,300,150,160,]
console.log(food);
console.log(food[2],price[0]);
console.log(price[3],food[0]);

// Array Program
const Sname=["Abhay","Anisha","Ani","Advik","Advika","Amarjeet"]
const Schoolname=["Modern school","Narayana school","DAV School","SGD School","Loyla","Don Bosco"]
const Age=[11,12,13,15,16]
console.log(Sname,Schoolname,Age);
console.log(Sname[2]);
console.log(Sname[1],Schoolname[1],Age[1]);
console.log(Sname[3],Schoolname[3],Age[3]);

// Array
 let Trade=["CSA","COPA","WELDER","MACHINIST","IT","IBM"]
 let Student=["Priyanka","Tulsi","Satyam","Somu","Ani"]
 console.log(Trade);
 console.log(Student);
 console.log(Student[2],Trade[2]);
 console.log(Trade[0],Student[4]);
 
 // Array Program
 let m=[20,60,40,12]
   for (let i=1; i>=55; i++) {
    console.log("iteration;", m);
   }


 