//CLASS
// Class is a template for creating objects.
// It encapsulation data and functions that operates on that data.

//class 1
class Person{   
constructor(name1,age2,address3){
    this.name=name1;
    this.age=age2;
    this.address=address3;
}
}
const hmmm=new Person ("priyanka",22,"JH");
const okk=new Person("Pritha",23,"BR");
console.log(hmmm);
console.log(hmmm.name);
console.log(okk);

// class 2
 class Market{
    constructor(name,city,address){
    this.name=name;
    this.city=city;
    this.address;
    }
 }
const Market1=new Market("Chirkunda","Dhanbad","JH");
const Market2=new Market("Purana bazar","Dhanbad","JH");
const Market3=new Market("Hatia","Barakar","JH");
console.log(Market1);
console.log(Market2);
console.log(Market3);
