
// An object is a collection of key value pairs (properties)
// Objects are used to store multiple values of a single entity.
// Keys are strings (or symbols) and values can be any data type.

// object

const candidate={
    name:"Priyanka",
    age: 22,
    address: "Jharkhand",
    mobile: 7779996756,
    country: "India"

}
console.log(candidate.age);
console.log(candidate.name, candidate.age, candidate.address, candidate.mobile,candidate.country);

// object2
// CITS
 const Branch={
    b1:"CSA",
    b2:"IT",
    b3:"M.SC",
    b4:"B.SC",  
 }
 console.log(Branch);
 console.log(Branch.b1,Branch.b2,Branch.b3, Branch.b4);

 // object3
 const school={
    sname:"SGD SCHOOL",
    cname:"Priyu Kumari",
    id:"Admit card",
    sclass:"six",
    rno: 2,
    sec: "A",
    cteach:"Abhijeet Kumar"
 }
console.log(school);
console.log(school.sname,school.cname,school.id,school.sclass,school.cteach);

// obejct4
const menu={
    m1:"Pasta",
    m2:"Chowmin",
    m3:"chole Bhatura",
    m4:"Kulcha",
    m5: "Butter paneer",
}
console.log(menu);
console.log(menu.m1);
console.log(menu.m1,menu.m2,menu.m3,menu.m4,menu.m5);

// obejct5
 const car={
   brand1:"TOYOTA",
   brand2:"THAR",
   brand3:"DEFENDER",
   brand4:"NANO",
   brand5:"SCORPIO",
 }
 console.log(car);
 console.log(car.brand1,car.brand2,car.brand3,car.brand4,car.brand5);
 
 